#!/usr/bin/env python3
"""Parse JOB SQL templates, derive single-table predicates, estimate selectivities,
and write results to q{n}_filters.json for the optimizer.

Usage (examples):
    cd <repo-root>
    python3 ispg/imdb/job/imdb_job_query_compiler.py --query q1
    python3 ispg/imdb/job/imdb_job_query_compiler.py --all
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import duckdb
import sqlglot
from sqlglot import exp

REPO_ROOT = Path(__file__).resolve().parents[3]
BASE_DIR = Path(__file__).resolve().parent
SQL_FILE = BASE_DIR / "q1~q33.sql"
SCHEMA_SQL = REPO_ROOT / "datasets" / "imdb" / "imdb_raw" / "schematext.sql"
RAW_DIR = REPO_ROOT / "datasets" / "imdb" / "imdb_raw"
FILTERS_DIR = BASE_DIR / "query_filters"


@dataclass
class TableInfo:
    name: str
    columns: List[str]


@dataclass
class PredicateStats:
    expression_sql: str
    matched_rows: int
    total_rows: int
    selectivity: float


class SchemaCatalog:
    """Very small helper to parse schematext.sql (generated by IMDB dataset)."""

    def __init__(self, schema_sql: Path) -> None:
        self.schema_sql = schema_sql
        self.tables: Dict[str, TableInfo] = {}
        self._parse()

    def _parse(self) -> None:
        create_re = re.compile(r"^CREATE TABLE (\w+)\s*\(", re.IGNORECASE)
        current_table: Optional[str] = None
        columns: List[str] = []

        with self.schema_sql.open("r", encoding="utf-8") as f:
            for raw_line in f:
                line = raw_line.strip()

                if not line or line.startswith("--"):
                    continue

                match = create_re.match(line)
                if match:
                    if current_table is not None:
                        self.tables[current_table] = TableInfo(
                            name=current_table, columns=columns
                        )
                    current_table = match.group(1).lower()
                    columns = []
                    continue

                if current_table is None:
                    continue

                if line.startswith(")"):
                    # End of CREATE TABLE block
                    self.tables[current_table] = TableInfo(
                        name=current_table,
                        columns=columns,
                    )
                    current_table = None
                    columns = []
                    continue

                # Column definition: <name> <type> ...
                col_def = line.rstrip(",")
                parts = col_def.split()
                if not parts:
                    continue
                col_name = parts[0].strip('"').lower()
                if col_name in {"primary", "unique", "constraint"}:
                    # Skip constraints
                    continue
                columns.append(col_name)

    def get(self, table: str) -> TableInfo:
        key = table.lower()
        if key not in self.tables:
            raise KeyError(f"Table not found in schema: {table}")
        return self.tables[key]


class DuckDBCatalog:
    """Register raw CSV tables as DuckDB views for quick selectivity estimation."""

    def __init__(self, schema: SchemaCatalog, raw_dir: Path) -> None:
        self.schema = schema
        self.raw_dir = raw_dir
        self.conn = duckdb.connect()
        self._registered: Dict[str, bool] = {}

    def ensure_view(self, table: str) -> None:
        table_l = table.lower()
        if self._registered.get(table_l):
            return

        info = self.schema.get(table_l)
        csv_path = self.raw_dir / f"{table_l}.csv"
        if not csv_path.exists():
            raise FileNotFoundError(f"CSV not found for table '{table_l}': {csv_path}")

        # Detect delimiter (some IMDB CSVs use comma, others use '|')
        with csv_path.open("r", encoding="utf-8", errors="ignore") as sample_file:
            sample = sample_file.readline()
        delimiter = "|" if "|" in sample and sample.count("|") >= sample.count(",") else ","

        # Build DuckDB read_csv_auto invocation with explicit column map (all as VARCHAR)
        columns_list = ", ".join(f"'{col}'" for col in info.columns)
        view_sql = f"""
            CREATE OR REPLACE VIEW {table_l} AS
            SELECT *
            FROM read_csv_auto(
                '{csv_path.as_posix()}',
                delim='{delimiter}',
                header=FALSE,
                ignore_errors=TRUE,
                strict_mode=FALSE,
                quote='"',
                escape='"',
                sample_size=-1,
                parallel=FALSE,
                names=[{columns_list}]
            );
        """
        self.conn.execute(view_sql)
        self._registered[table_l] = True

    def count(self, table: str, where_sql: Optional[str] = None) -> int:
        self.ensure_view(table)
        if where_sql:
            query = f"SELECT COUNT(*) FROM {table} WHERE {where_sql}"
        else:
            query = f"SELECT COUNT(*) FROM {table}"
        result = self.conn.execute(query).fetchone()
        return int(result[0]) if result else 0


def read_queries(sql_file: Path) -> Dict[str, str]:
    text = sql_file.read_text(encoding="utf-8")
    pattern = re.compile(r"q(\d+):\s*(SELECT.*?);", re.IGNORECASE | re.DOTALL)
    queries: Dict[str, str] = {}
    for match in pattern.finditer(text):
        qname = f"q{match.group(1)}"
        sql = match.group(2).strip()
        queries[qname] = sql
    if not queries:
        raise RuntimeError(f"Failed to parse any query from {sql_file}")
    return queries


def split_conjuncts(expr: exp.Expression) -> Iterable[exp.Expression]:
    if isinstance(expr, exp.And):
        yield from split_conjuncts(expr.left)
        yield from split_conjuncts(expr.right)
    else:
        yield expr


def referenced_tables(expr: exp.Expression) -> List[str]:
    tables: List[str] = []
    seen: set[str] = set()
    for col in expr.find_all(exp.Column):
        table = (col.table or "").lower()
        if table and table not in seen:
            tables.append(table)
            seen.add(table)
    return tables


def strip_alias_simple(expr_sql: str, alias: str) -> str:
    # Replace occurrences like alias.column -> column (case-insensitive)
    return re.sub(rf"\b{re.escape(alias)}\.", "", expr_sql, flags=re.IGNORECASE)


def estimate_predicates(
    alias: str,
    table: str,
    predicates: List[exp.Expression],
    catalog: DuckDBCatalog,
) -> Tuple[List[PredicateStats], float]:
    alias_l = alias.lower()
    table_l = table.lower()

    if not predicates:
        total = catalog.count(table_l)
        stats = PredicateStats(
            expression_sql="TRUE",
            matched_rows=total,
            total_rows=total,
            selectivity=1.0,
        )
        return [stats], 1.0

    predicate_stats: List[PredicateStats] = []
    catalog.ensure_view(table_l)
    total_rows = catalog.count(table_l)

    # Combine predicates with AND for joint selectivity
    combined_expr = None
    for pred in predicates:
        combined_expr = pred if combined_expr is None else exp.and_(combined_expr, pred)

    combined_sql = combined_expr.sql(dialect="postgres") if combined_expr else "TRUE"
    where_sql = strip_alias_simple(combined_sql, alias_l)
    matched_rows = catalog.count(table_l, where_sql)
    combined_selectivity = (matched_rows / total_rows) if total_rows else 1.0

    # Individual predicate stats (still evaluated under the table only)
    individual_exprs: List[str] = []
    for pred in predicates:
        pred_sql_alias = pred.sql(dialect="postgres")
        pred_sql = strip_alias_simple(pred_sql_alias, alias_l)
        matched = catalog.count(table_l, pred_sql)
        sel = (matched / total_rows) if total_rows else 1.0
        individual_exprs.append(pred_sql_alias)
        predicate_stats.append(
            PredicateStats(
                expression_sql=pred_sql_alias,
                matched_rows=matched,
                total_rows=total_rows,
                selectivity=sel,
            )
        )

    # Append combined stat at the end for convenience
    predicate_stats.append(
        PredicateStats(
            expression_sql=" AND ".join(individual_exprs)
            if len(individual_exprs) > 1
            else (individual_exprs[0] if individual_exprs else "TRUE"),
            matched_rows=matched_rows,
            total_rows=total_rows,
            selectivity=combined_selectivity,
        )
    )

    return predicate_stats, combined_selectivity


def compile_query(
    qname: str,
    sql: str,
    catalog: DuckDBCatalog,
    output_dir: Path,
) -> None:
    expr = sqlglot.parse_one(sql, read="postgres")
    alias_to_table: Dict[str, str] = {}
    table_order: List[Tuple[str, str]] = []
    for table in expr.find_all(exp.Table):
        # Base table name
        table_id = table.this
        if isinstance(table_id, exp.Identifier):
            table_name = table_id.name.lower()
        else:
            table_name = table.this.sql(dialect="postgres").lower()

        # Table alias (fallback to table name if absent)
        alias_expr = table.alias
        if alias_expr:
            if isinstance(alias_expr, exp.TableAlias) and isinstance(alias_expr.this, exp.Identifier):
                alias_name = alias_expr.this.name.lower()
            elif isinstance(alias_expr, str):
                alias_name = alias_expr.lower()
            else:
                alias_name = alias_expr.sql(dialect="postgres").lower()
        else:
            alias_name = table_name

        alias_to_table[alias_name] = table_name
        table_order.append((alias_name, table_name))

    where_clause = expr.args.get("where")
    single_table_preds: Dict[str, List[exp.Expression]] = {alias: [] for alias in alias_to_table}
    join_edges: List[Dict[str, object]] = []
    residual_conditions: List[str] = []

    if where_clause is not None:
        for predicate in split_conjuncts(where_clause.this):
            tables = referenced_tables(predicate)
            if len(tables) == 1:
                alias = tables[0]
                single_table_preds.setdefault(alias, []).append(predicate)
            elif len(tables) == 2 and isinstance(predicate, exp.EQ):
                left_expr = predicate.left
                right_expr = predicate.right
                if isinstance(left_expr, exp.Column) and isinstance(right_expr, exp.Column):
                    left_alias = (left_expr.table or tables[0]).lower()
                    right_alias = (right_expr.table or tables[1]).lower()
                    join_edges.append(
                        {
                            "condition": predicate.sql(dialect="postgres"),
                            "left": {
                                "alias": left_alias,
                                "column": left_expr.name,
                            },
                            "right": {
                                "alias": right_alias,
                                "column": right_expr.name,
                            },
                        }
                    )
                else:
                    residual_conditions.append(predicate.sql(dialect="postgres"))
            else:
                # Multi-table predicates / non-simple conditions are stored as residual
                residual_conditions.append(predicate.sql(dialect="postgres"))

    alias_order_unique = []
    seen_aliases: set[str] = set()
    for alias, table in table_order:
        if alias in seen_aliases:
            continue
        seen_aliases.add(alias)
        alias_order_unique.append((alias, table))

    aliases_output: Dict[str, Dict[str, object]] = {}
    for alias, table in alias_order_unique:
        predicates = single_table_preds.get(alias, [])
        pred_stats, combined_selectivity = estimate_predicates(
            alias=alias,
            table=table,
            predicates=predicates,
            catalog=catalog,
        )
        aliases_output[alias] = {
            "table": table,
            "filters": [
                {
                    "expression": stat.expression_sql,
                    "matched_rows": stat.matched_rows,
                    "total_rows": stat.total_rows,
                    "selectivity": stat.selectivity,
                }
                for stat in pred_stats[:-1]
            ],
            "combined": {
                "expression": pred_stats[-1].expression_sql,
                "matched_rows": pred_stats[-1].matched_rows,
                "total_rows": pred_stats[-1].total_rows,
                "selectivity": combined_selectivity,
            },
        }

    alias_to_tag = {alias: idx for idx, (alias, _) in enumerate(alias_order_unique)}

    vertices = [
        {
            "tag_id": alias_to_tag[alias],
            "alias": alias,
            "table": table,
            "combined_selectivity": aliases_output[alias]["combined"]["selectivity"],
            "combined_expression": aliases_output[alias]["combined"]["expression"],
            "filters": aliases_output[alias]["filters"],
        }
        for alias, table in alias_order_unique
    ]

    edges = []
    for idx, edge in enumerate(join_edges):
        left_alias = edge["left"]["alias"]  # type: ignore[index]
        right_alias = edge["right"]["alias"]  # type: ignore[index]
        if left_alias not in alias_to_tag or right_alias not in alias_to_tag:
            residual_conditions.append(edge["condition"])  # type: ignore[arg-type]
            continue
        edges.append(
            {
                "edge_id": idx,
                "left_alias": left_alias,
                "right_alias": right_alias,
                "left_tag": alias_to_tag[left_alias],
                "right_tag": alias_to_tag[right_alias],
                "left_column": edge["left"]["column"],  # type: ignore[index]
                "right_column": edge["right"]["column"],  # type: ignore[index]
                "condition": edge["condition"],
            }
        )

    output = {
        "query": qname,
        "sql": sql,
        "aliases": aliases_output,
        "vertices": vertices,
        "edges": edges,
        "residual_conditions": residual_conditions,
    }

    out_path = output_dir / f"{qname}_filters.json"
    out_path.write_text(json.dumps(output, indent=2), encoding="utf-8")
    print(f"[INFO] Wrote {out_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compile JOB SQL filters and estimate selectivities.")
    parser.add_argument("--query", dest="queries", action="append", help="Only process the specified query (e.g., q1)")
    parser.add_argument("--all", action="store_true", help="Process all queries")
    args = parser.parse_args()

    queries = read_queries(SQL_FILE)

    if args.queries and not args.all:
        target = {q.lower() for q in args.queries}
        queries = {name: sql for name, sql in queries.items() if name.lower() in target}
        if not queries:
            raise SystemExit("Specified query not found. Expected name format: qN")

    schema_catalog = SchemaCatalog(SCHEMA_SQL)
    duck_catalog = DuckDBCatalog(schema_catalog, RAW_DIR)

    FILTERS_DIR.mkdir(parents=True, exist_ok=True)

    for qname, sql in queries.items():
        compile_query(qname, sql, duck_catalog, FILTERS_DIR)


if __name__ == "__main__":
    main()
